---
- name: "Build container with ansible"
  hosts: localhost
  tasks:
    - name: stop running container
      command: docker stop podinfo
      ignore_errors: yes

    - name: remove stopped container
      command: docker rm podinfo
      ignore_errors: yes

    - name: remove used image
      command: docker rmi flask-app-image
      ignore_errors: yes

    - name: build docker image from dockerfile
      command: docker build -t flask-app-image .

    - name: create tag to image
      command: docker tag flask-app-image sami4rhimi/flask-app-image:v01

    - name: push image to dockerhub
      command: docker push sami4rhimi/flask-app-image:v01

    - name: run container from image
      command: docker run -d --name podinfo sami4rhimi/flask-app-image:v01