---
- name: "Build image with ansible"
  hosts: localhost
  tasks:
    - name: add file to git repo
      command: git add .

    - name: commit changes
      command: git commit -m "refine the code again"

    - name: push changes
      command: git push origin main
      
    - name: stop running container
      command: docker stop podinfo
      ignore_errors: true

    - name: remove stopped container
      command: docker rm podinfo
      ignore_errors: true

    - name: remove used image
      command: docker rmi  sami4rhimi/flask-app-image
      ignore_errors: true

    - name: build docker image from dockerfile
      command: docker build -t flask-app-image .

    - name: create tag to image
      command: docker tag flask-app-image sami4rhimi/flask-app-image

    - name: push image to dockerhub
      command: docker push sami4rhimi/flask-app-image

    - name: run container from image
      command: docker run -d --name podinfo sami4rhimi/flask-app-image